### PR TITLE
Fix: broken build; update to core22

### LINKED ISSUE #21: Update to 4.3.1 (is this snap still being maintained?)
### What changes would you like?

Current version of TheLounge is 4.3.1. I see Stable and Beta branches of the snap are still on 4.2.0, while edge is still on 4.3.0. It seems as though the snap might not be maintained?

### Any extra information?

_No response_

### LINKED ISSUE #22: Update to 4.4.0
### What changes would you like?

Hi, could we get the 4.4 update? a lot of stuff got updated and/or rewritten. Thank you

### Any extra information?

[https://github.com/thelounge/thelounge/releases/tag/v4.4.0](url)

### PR DESCRIPTION
**Pull request by lucyllewy**
* Broken build fixed by upgrading to core22
* Add `npm-deps` part with a face `package.json` to work-around the npm plugin weirdness breaking the build step ordering that we need.

fixes: #21 
fixes: #22

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
@lucyllewy any idea why pack is failing?

**Comment by lengau** [comment]
Looks like the pack is failing because `bin/thelounge` doesn't exist. (I used `snapcraft try` and then `snap pack` to work around https://github.com/snapcore/snapcraft/issues/4499.)

```
lengau@ratel:~/Projects/thelounge$ snap pack --filename thelouge_4.4.1_amd64.snap --compression xz prime/ .
2024/01/16 11:00:28.931547 container.go:239: in snap "thelounge": path "bin/thelounge" does not exist
error: cannot pack "prime/": snap is unusable due to missing files
```

Maybe we need the `yarn global add thelounge` command like they have in the docs? https://thelounge.chat/docs/install-and-upgrade#from-npm-releases

**Comment by lucyllewy** [comment]
I don't know why it failed in the CI. It succeeded on my system. (my wired internet is offline until I move home so I will prolly struggle to get a look at it for a bit)

**Review by lengau — COMMENTED** [review]
I'm just commenting here to remove this from my review queue :-)

Please let me know when you'd like a new review.

**Comment by lucyllewy** [comment]
> Please let me know when you'd like a new review.

I've updated the branch so you can add it back to your queue now.

**Comment by jnsgruk** [comment]
Feels like if we're going to trick the npm plugin with a fake package.json, maybe we should just not use the npm plugin at all and just override the build?

Might also be worth looking at the proxy config for yarn - I don't think this will immediately work for lp builds - see the (recent) signal snap commit history which has some clues in it!

**Comment by lucyllewy** [comment]
I successfully built with `snapcraft remote-build`, which should be close to the build service's config?

**Comment by lucyllewy** [comment]
also the fake package.json is purely to get nodejs installed and kept up to date. Its the easiest way to keep it updated without trying to duplicate effort and code by copying the npm plugin's download logic.

**Review by jnsgruk — APPROVED** [review]

**Pull request merged**
